dataset_params:
  train_path: '../data/img_align_celeba/img_align_celeba/train/'
  valid_path: None #'../data/img_align_celeba/img_align_celeba/valid/'
  limit_size: False
  size_limit: -1

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0001
  beta_end : 0.02

model_params:
  img_size : [128,128]
  time_emb_dim : 256
  channels : [32, 64, 128, 256, 512]
  down_attn: [False, False, False, True]
  down_channel_indices: [[0,0], [0,1], [1,2], [2,3]] # in, out indices into channels[] for each down layer

  mid_attn:  [False, False, False]
  mid_channel_indices: [[3,4], [4,4], [4,3]] # in, out indices into channels[] for each mid layer

  up_attn:   [True, False, False]
  up_channel_indices: [[3,2], [2,1], [1,0]] # in, out indices into channels[] for each up layer
  num_heads : 8
  dim_head : 64
  dropout: 0.1 
  attn_dropout: 0.1

train_params:
  log_dir: './lightning_logs/'
  batch_size: 96
  num_epochs: 400
  checkpoint_name: None #'/home/mark/dev/diffusion/lightning_logs/version_8/checkpoints/epoch=222-step=406752.ckpt'
  log_every_nsteps: 1000
  accelerator: 'gpu'
  devices: 2
  save_top_k: 5
  checkpoint_every_n_epochs: 1
  monitor: 'loss'
  mode: 'min'

